name: .NET

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET 2.1
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.1.x
    - name: Setup .NET 5.0
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Set Version
      run: dotnet SetVersion.dll 5.0.1.${{ github.run_number }}
    - name: Build AmbientServices
      run: dotnet build AmbientServices -c Release
    - name: Build AmbientServices.Samples
      run: dotnet build AmbientServices.Samples -c Release
    - name: Build AmbientServices.Test.DelayedLoad
      run: dotnet build AmbientServices.Test.DelayedLoad -c Release
    - name: Build AmbientServices.Test
      run: dotnet build AmbientServices.Test -c Release
    - name: Package
      run: dotnet pack AmbientServices -c Release
    - name: Test .NET 5
      run: dotnet test -c Release -f net5.0 --collect:"XPlat Code Coverage" --logger:"trx;LogFileName=unit.testresults.trx"
    - name: Test .NET Core 2.1
      run: dotnet test -c Release -f netcoreapp2.1
    - name: Publish
      run: dotnet nuget push AmbientServices/bin/Release/AmbientServices.5.0.1.${{ github.run_number }}.nupkg -k ${{ secrets.NUGET_API_KEY }} -s https://api.nuget.org/v3/index.json